name: project_moneyTracker_kel2
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  fl_chart: ^0.55.0  # downgrade biar compatible Dart 2.19
  calendar_agenda:
    path: dev_lib/calendar_agenda
  card_swiper:
    path: dev_lib/card_swiper


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/font/Inter-Bold.ttf
          weight: 700

# --- BAGIAN PENTING: JURUS PAKSA VERSI ---
# Ini memaksa seluruh aplikasi (termasuk SDK) menggunakan versi yang kita mau
dependency_overrides:
  intl: ^0.18.1
  table_calendar: ^3.0.9