name: trackizer
description: A new Flutter project fokus pada fitur Settings.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Library buat bahasa & format tanggal (penting buat jam realtime lo)
  flutter_localizations:
    sdk: flutter

  # --- External Packages (Yang WAJIB buat Settings) ---
  shared_preferences: ^2.2.0            # Simpen toggle dark mode & jam
  flutter_local_notifications: ^17.0.0  # Biar hp user bunyi "Ting!"
  timezone: ^0.9.2                      # Biar notif nggak salah jam
  cupertino_icons: ^1.0.2               # Buat icon switch ala iPhone

  # --- Dependency Overrides (Biar intl nggak rewel) ---
dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Pastiin folder ini ada, atau lo bakal kena error 'Asset not found'
  assets:
    - assets/img/

  # Font Inter biar aplikasi lo kelihatan mahal, bukan kayak tugas anak SD
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/font/Inter-Bold.ttf
          weight: 700